### ISSUE TITLE
Recommended bitcoinj fork for BSV

### ISSUE THREAD

**Issue by mogray5** [bitcoinj-sv/bitcoinj-sv#1]
Apologies if this is a dumb question but Is this bitcoinj-sv fork the recommended bitcoinj fork to use on the BSV chain?

In the developer tools section of  https://bitcoinsv.io the bitcoinj link points to https://bitcoinj.github.io/ which I thought was a core only compatible version.

This link says the CashPay team has the bitcoinj version for BSV as well:  https://coingeek.com/hivr-chooses-bitcoin-sv-cashpay-releases-bsv-java-protocol/

Thanks,
Wayne

**Comment by Danconnolly** [comment]
Hi, good point. I forgot about that version. I'd stick with them for now, the repo is here: https://gitlab.com/lighthouseCash-dev/bitcoinj-cash/tree/bsv-0.14.7

This version is not ready.

**Comment by mogray5** [comment]
Ok thanks.  Will try cashpay's version.
